version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
test: off

environment:
  publishUsername:
    secure: +of8YobtR9CSGWdE1ttUTA==
  publishPassword:
    secure: 5D5/0OnhJtHvQVE1Qgp69VsQ6VrJ0k+1lQ9SLgjReLawxfvzv6WDozfh9Mln/pp4A3XjnRT9/JTadxNrzCHkAw==
  TEMPLATEDOTNETTOOLSPATH: C:\Users\appveyor\.dotnet\tools
  TEMPLATE_REPORT_PATH_TO_IGNORE_FILE: C:\projects\dotnet-new-web\src\TemplatesConsole\packages-to-ignore.txt

before_build:
- pwsh: dotnet restore

build:
  project: dotnet-new-web.sln
  verbosity: normal

after_build:
- pwsh: ./appveyor.ps1

artifacts:
- path: src\TemplatesApi\wwwroot\template-report-updated.json
- path: output\release\netcoreapp3.1\publish\template-report.json
  name: template-report.from-tools-folder.json
- path: src\TemplatesConsole\package-names-to-ignore.json
- path: ls-out.txt
- path: src\TemplatesConsole\packages-to-ignore.txt
