using System;
using System.Collections.Generic;
using System.Text;

namespace TemplatesShared {
    internal static class Strings {
        internal static readonly string NuGetQueryBaseUrl = "https://azuresearch-usnc.nuget.org/query";

        internal static readonly string PackagesToIgnore = @"eTemplates.Shared.Net45
TrackableEntities.CodeTemplates.Shared.Portable
Transformer.NET
TransientErrorHandler
Trarc.Web.TemplateEngine
Triarc.Web.Bundle.Angular
Tribe.Template
TS.CodeGenerator
TsSoft.Docx.TemplateEngine
TweetSharp
TweetSharp.WindowsPhone
TweetSharp-Unofficial
twitter.bootstrap.mvc4.templates
TwitterBootstrapMVC3Template
TXTextControl.Web
TypeLess.Mail
TypeLite.Lib
TypeScriptAngularJsProxyGenerator
TypeScriptGenerator
typescripttemplates
UcdArch.Templates.Mvc
uibuilder
UmbCodeGen
UmbracoTemplateEngine
Underscore.Templates.MsBuild
UnderscoreBundler
Underskrift.Client
Unic.PackMan
Unic.PackMan.Core
Unic.PackMan.Core.Sitecore6
Unic.PackMan.Core.Sitecore7
Unic.PackMan.Sitecore6
Unic.PackMan.Sitecore7
Unicorn
Unicorn.Core
UnifiedFramework
UnistrokeRecognizer.UWP
UnitTestGenerator
UnitTestGenerator.Extensions.Composition
Unofficial.Microsoft.VisualStudio.TextTemplating
Unofficial.Nustache
UriTemplate.Core
uri-templates.TypeScript.DefinitelyTyped
UriTemplateString
url-template.TypeScript.DefinitelyTyped
Utils.NET
Vash
Veil
Veil.Handlebars
Veil.SuperSimple
vici.core
Vintasoft.Imaging.FormsProcessing
Vintasoft.Imaging.FormsProcessing.Wpf.UI
VirtualPathTemplates
VirtualTemplates
VsoApi.MsAgile.Entities
vspte
vspte.vs2012
VSSDK.TemplateWizardInterface
VSSDK.TemplateWizardInterface.10
VSSDK.TemplateWizardInterface.11
VSSDK.TemplateWizardInterface.12
VSSDK.TemplateWizardInterface.8
VSSDK.TemplateWizardInterface.9
warmup
Watt
WebApi.ControllerTemplates
WebApi.Setup.Template
WebApi.Template
WebAPIDoodle.Bootstrap
WebAPIDoodle.Bootstrap.Sample
WebAPIDoodle.Bootstrap.Sample.Complex
WebApiProxyClient
WebApiProxyClientJS
WebHttpBehaviorExtensions
WebMarkupMin.Core
WebSharper.Templates
Weingartner.DotLiquidExtensions
Westwind.RazorHosting
Win8Controls
WinJs-HTML-Template
WINRTNotifications
Wired.Razor
Wishlist.Template
WordCleaner
WorkAByte.NuGet.Packager.Core
WPF.Notifier
wpflipping
WpfTemplateLib.dll
Wrox.ProMvc3.Ajax.Templates
Wrox.ProMvc4.Ajax.Templates
wtl
WuffProjects.CodeGeneration
wxWidgetsTemplate
XAct.IO.TemplateEngines.NVelocity
XAct.IO.TemplateEngines.RazorHost
XAct.IO.TemplateEngines.StringTemplate
XActDependency.Antlr3.StringTemplate
XamarinFormsExtensions.Controls
xercesc
Xerneas.Template
XperiAndri.Interactivity.Orientation
Xpertdoc.TemplateManager.AddIn
Xpertdoc.TemplateManager.Operations
Xpertdoc.TemplateManager.Operations.Word
xscaffolding
xscaffolding.tempates
XsdClassGen
XSockets.ItemTemplates
Xtensive.Orm.AppConfig
XtraLiteTemplates
Y3
Yeoman.VisualStudio
yesmarket.Templating.Razor
Yodii.Script
ZenTemplates
ZenTemplates.HttpHandler
ZKWeb.Fork.DotLiquid
ZumeroDataGrid
Zurb_Foundation_MVC3
Zurb_Foundation_MVC3_Demo
AngularCSharp
AspNetMvc.Template.AccountController
AspNetMvc.Template.Empty
AspNetMvc.Template.Internet
Black.Beard.Sdk.Net.Mails
BLDR.Test
Boilerpipe.Net
Boilerplate.AspNetCore
Boilerplate.AspNetCore.Razor
Boilerplate.AspNetCore.Swagger
Boilerplate.AspNetCore.TagHelpers
Boilerplate.Web.Mvc5
Boilerplate.Web.Mvc6
Boilerplate.Web.Mvc6.Razor
Boilerplate.Web.Mvc6.TagHelpers
BorisMoore.JsRender
Catapult.Peanut.Atlatl
Code4U
CodeSmith.Generator.EntityFramework.WebAPI
ConsulTemplate.Core
DD.CBU.CaasDeploy.Library
DD.CBU.CaasDeploy.Orchestration.Docs
Enjoy.Templates
Freya.Routers.Uri.Template
Freya.Routers.Uri.Template.Hopac
Freya.Types.Uri.Template
FsMessageTemplates
FsMtParser
Fx.AppServer.Main
Happy
HTTPlease
HTTPlease.Core
ImmutableObjectGraph.T4
knockroute
Leprechaun
Mail.Razor
mantle-worker-azure-cloud-service-role-host
mantle-worker-console-host
mantle-worker-template
mantle-worker-windows-service-host
MessageTemplates
Microsoft.AspNet.DynamicDataTemplates.CS
Microsoft.Data.Services.Client.T4
MonoGame.Template.Platformer2D
mustache-portable.kre
NecroNetToolkit.RepositoryGenerator
Newtonsoft.Json
NokauTemplate
NPolyglot.Templating.Handlebars
Octopus.Tfs
pecan-waffle-vs
Protobuild.Template.Console
Protobuild.Template.Library
Protogame.Template.Asteroids
Protogame.Template.Blank
Protogame.Template.Platformer
Rackspace.Net.UriTemplate
RapidSP.SqlServer
RazorEmailCore
RazorEngine.Roslyn
Reactive.Caliburn.Avalon.Metro
Reactive.Caliburn.Metro
SEBSET
Shared.Images
Shared.Plugins
Shared.Scripts
Shared.Styles
Shared.Views
ShortBus.Scaffolding
Simplr.MVC.WebsiteTemplate
SSW.DataOnion.DbContextGenerator.EF6
StackExpress.Razor
StackExpress.Razor2
Stubble.All
Stubble.Core
Stubble.Extensions.JsonNet
Stubble.Extensions.Loaders
Stubble.Extensions.SystemData
Swagger.WebApiProxy
Tempest
Tempest.Generator.Empty
Tempest.Generator.New
TemplateJS
Temptress
TunnelVisionLabs.Net.UriTemplate
Turnip.MSBuild.Task
VsTemplar
Xania.EntityFramework
Zafir.Templates
Kralizek.Lambda.Template
StringTemplate4
Futurez.Xrm.Tools.DocTemplateManager
DotLiquid
Spring.Template.Velocity
ITLec.EmailTemplateManager
Takenet.MessagingHub.Client.WebTemplate
AfominDotCom.NgProjectTemplate.Server
Takenet.MessagingHub.Client.CustomerSuccess.Template
UlbeGroup.TemplateManager
EnterpriseLibrary.Data.Template
EdtterTemplate
bgTeam.ProjectTemplate
SupercondActor.Utils.TemplateEngine
AppMobiWP8SimpleJqMobiTemplate
Express.Template
BizTalkProjectTemplate
SSRD.AdminUI.Template
AppMobiWP8JqMobiKitchenSinkTemplate
Angular2.Net-Core-Template
GGM.TemplateResolver.Razor
MvcCodeTemplate.Mvc
Template10.Services.SecretService
XActDependency.Antlr3.StringTemplate
QiQiTemplate
Hyperion.DataAcquisition.Template
Xpertdoc.TemplateManager.Operations
ecu-mvc-template
BOP.ProjectTemplate
Messaia.Net.Base.Template.ViewModels
Takenet.MessagingHub.Client.HostTemplate
EventCentric.Node.WebTemplate
Dynamicweb.TemplateCompatibilityPack
Messaia.Net.Base.Template.DataAccess
Koshu.PluginTemplate
NMP.Macros.TemplateProject
SimpleTrading.GrpcTemplate
NetCoreKit.Template.gRPC.Standard
Gsl.Template
Lykke.AlgoStore.CSharp.AlgoTemplate.Abstractions
UmbracoTemplateEngine
Platform.Exceptions.TemplateLibrary
wk.TemplateParser
SbsTemplateNet
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Console.Test
SourceCode.Clay.Net.UrlTemplate
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Recipe
Salous.Utilities.HelperTextTemplate
Webezi.Abp.TemplateKit
iOnTech.SimpleJsonTemplate
NetCoreKit.Template.gRPC.MongoDb
CoreRestTemplate
AspNetAppOfflineTemplate
JavaScriptTemplateCompiler.Tool
NetCoreKit.Template.Rest.Standard
NetCoreKit.GrpcTemplate.EfCore
BlueLeet.UCodeFirst.DefaultTemplate
Knockout.Bootstrap.TemplateStore.SystemWeb
NetCoreKit.GrpcTemplate.Standard
Template10.Xaml.Converters
Template10.Services.CompressionService
Carubbi.LayoutTemplateEngine
Platform.Converters.TemplateLibrary
GoC.WebTemplate-Components.Framework
Template_Delivery
Template10.Services.ResourcesService
XamarinFormsTemplateCreater
Carubbi.LayoutTemplateEngine.Interfaces
HelloWorldNuGetTemplate
OrleansGrain.NetStandard.ProjectTemplate
MicroservicesTemplate.Common
SpiderX.Template
Yeoman.VisualStudio
Connector_Template5
DotNet.Template.CSharp.Package
Docx.Templater
Sandra.Templating
GoC.EWS.Components.WSMasterTemplate
V33_Connector_Template331
ChameleonForms.TwitterBootstrap3
HTTPlease
JD_ReportRepAcess
YadaYada.Bisque.Aws
Boerman.Mail
MVVMTemplateSelection
Daisytech.Web.Events
OpenWaves.Templates.RssFeed
Foundation3_Core
Docati.Api
Eighty
Redactor.Mvc.EditorTmpl
T4SQL.Base
CodeSmith.Generator.CSLA
Flxble.Templating
Unofficial.Nustache
TemplatorSyntaxBuildTask
HotTowel
Zahasoft.Skele.UnitTest
Eighty.AspNetCore
Y3
Dapper.Accelr8.Sql
Daisytech.Web.Tags
Shared.Scripts
MPSIT
TemplateBuilder
Antlr3.StringTemplate
Microsoft.Bot.Builder.TemplateManager
Freya.Routers.Uri.Template
XAct.IO.TemplateEngines.RazorHost
StringTemplate3
HTML5.Template
Freya.Routers.Uri.Template.Hopac
Stubble.Core
Calendar.Template
NPOI.Template
ExactTarget.EmailFromTemplate
DSharp.T4.DatabaseTemplate
AppMobiWP8SampleGameTemplate
ComponentPro.TemplateEngine
dng.Template
HotGlue.Template.Handlebars
Retyped.babel-template
Meadow.UnitTestTemplate
DynamicsCode.AccessTeamTemplateMover
mustache.js
Wishlist.Template
Messaia.Net.Base.Template.Repositories
HtmlTemplate
DynamicData.ImageFieldTemplate
Lykke.Service.TemplateFormatter.Client
Minion.Sitecore.StandardTemplate
VSSDK.TemplateWizardInterface.8
Tribe.Template
psake-template
Xerneas.Template
WebApi.Template
Messaia.Net.Base.Template.Api
Rodrigo.Web.Template
Retyped.lodash.template
com.azmisahin.domain.template.www
SmartTemplateProcessor
AppMobiWP8CameraTemplate
TNT.Core.Template.DataService
Akka.Interfaced.Templates
TemplateVersions.Tool
Messaia.Net.Base.Template.Services.Impl
Kralizek.Lambda.Template.Sqs
AppMobiWindows8FacebookTemplate
JQueryBindDataTemplate
Bakery.Template.VB2
XtraLiteTemplates
WordTemplateParser
AppMobiWindows8BlankTemplate
Xpertdoc.TemplateManager.Operations.Word
T4IncludeTemplateSamples
AppMobiWindows8JqMobiSimpleSampleTemplate
Essential.Templating.Razor
VL.PluginTemplate
iOnTech.SimpleJsonTemplate.Tests
Nop.Plugin.Payments.TemplateHolder
JavaScriptTemplateCompiler
IPEIT.TemplateResolver.Start
Trarc.Web.TemplateEngine
VSSDK.TemplateWizardInterface.11
XamlTemplateSelector
Otc.PdfTemplate.Abstractions
NativoPlus.Studio.ApiTemplate
Tmpps.Infrastructure.Template
NetCoreKit.GrpcTemplate.MongoDb
Zny.ServiceClient.Template
MvvmCaliburnTemplate
Richard.Template.OnionArch.Common
SuperXML
Bot.Builder.Utilities.TemplateManager
Rabbit.Communication.TextTemplate
Platform.Interfaces.TemplateLibrary
EventSourceGeneratorTemplateAttributes.Nuget
TemplateNuGetLib
ITOO.ExamEvalTemplate.BLL
GoC.WebTemplate-WebForms
Carubbi.LayoutTemplateEngine.NVelocity
Platform.Ranges.TemplateLibrary
EDDY.IS.Admin.Areas.Module.Template
DataTables.NetStandard.TemplateMapper
TemplateNuGetLib.symbols
Mxic.Framework.ServerComponent.ServiceTemplate
cloudscribe.Forms.ContentTemplate.Bootstrap4
DCI.Template.SQL.API
NetServices.Helper.RestTemplate
Carubbi.LayoutTemplateEngine.Razor3
LJH.Host.Template.Web
Essential.LogTemplate
CubeBuild.JSRazor
Refactored.Email
Dynamo.Templates
Wilinq.ProcessTemplates.Scrum
Vangiek.SysZeroTemplate.EntityFrameworkCore
Bastion.Senders.MessageTemplate.EntityFrameworkCore
ConsoleTemplate.NetCore.AliAbdoli
iAppHelpers
JinianNet.JNTemplate
OMS.Ice
SimpleHelpers.ConsoleUtils
TemP
Resta.UriTemplates
SimpleRazor
O2O.Resource
Daisytech.Web.DynamicForm
Daisytech.Web.Services.Subscriber
Daisytech.Web.Baidu.Map
OpenWaves.Templates.Errors
Colso.Xrm.AttributeEditor
OpenWaves.Templates.Pagination
Noodles.AspMvc.Templates
Foundation4.MVC4.Sass
EgoDB.Identity.SampleAdminLTE
Razor.Render.CommandLine
Dzonny.VSLangProj.Shared
Ulito.Shablon
wtl
Stubble.Helpers
Stubble.Extensions.JsonNet.Net45
t8
AdminLTE2.4.10
Templay
mustache.cs
Need.UI
HicknHack.Twofold.Core
Mailer.Handlebars
NVelocity
HandlebarsPDF
PI.Utilities.Mail.SmartFormat
Tang.Library.Razor
Mustache.Activities.UiPath
WebHttpBehaviorExtensions
GSF.Web.Mvc.Security
Mailr
EnterpriseFramework.Web
haugenapps.userscript
hieuvv.Dotliquid
TmpDistribution
DataBind
DynamicStackLayout
ServiceStack.Host.AspNet
TrackableData.Templates
FluffySpoon.AspNet.Templates
DangEasy.Detokenizing
ZeraSystems.CodeNanite.Schema
linq2db.MySql
RandomSolutions.PowerPointService
Simplet
Coding4Fun.VisualStudio.TextTemplating.Interfaces
Teco
Amazon.CDK.CloudFormation.Include
FluentEmailTemplates
N2CMS.Library
gfoidl.Translator.Tasks
N2CMS.Razor
AngularCRUD
Constellation.Foundation.Data
EmbeddedResourceVirtualPathProvider
JD_GetMyMemberships
linq2db.SQLite
linq2db.Access
SFSdotNet-Framework-Web-Mvc
Westwind.RazorHosting
JD_JobDetail
Indeco.webApp
JD_MemebershipDetail4
Microsoft.Bot.Builder.LanguageGeneration
PommaLabs.Liquimail.AspNetCore
N2CMS.Config
T4MVCVB
Mimeo
HBD.Mef.Mvc.Bootstrapper
JD_GetPostedMediaJob6
SFS-EFPOCO1-Services
JDD_GetUnfinishedJobMediaForJob_latest
JD_DownloadGroupMemebershipList
JD_GetPostedMediaJob_11
CANAPE.Net.Templates
JD_GetPostedMediaJob8
Naos.Build.Conventions.VisualStudioProjectTemplates.Recipe.Test
N2CMS.Management.NoZip
Benner.NoSQLRepository
LibRazorPdf
Naos.Build.Conventions.VisualStudioProjectTemplates.Domain.Test
Naos.Build.Conventions.VisualStudioProjectTemplates.Serialization.Json
Sphyrnidae.Server.Resource.Web
Microsoft.Orleans.Templates.Interfaces
Accord.Vision
ReCode
AttributeRouting.CodeTemplates.MVC4
RainbowCodeGeneration
Cassette.Web
Bootstrap.MVC.EditorTemplates
BumpAssemblyVersions
RazorEngineCore
linq2db.SqlCe
Reusable.OmniLog.ColoredConsoleRx
Vostok.Applications.AspNetCore
Win8Controls
GroupDocs.Parser
email-templates.TypeScript.DefinitelyTyped
Plainion.AppFw.Wpf
Mvc3CodeTemplatesCSharp
Fugu.Templates
T4MvcJs
Sphyrnidae.Client
Breeze.Server.WebApi.EF
linq2db.Informix
T4.Signalr.Hubs.TypeScriptGenerator
Codge.BasicModel.Templates.CS
Baffi
Microsoft.AspNet.WebApi.ScaffolderTemplates.AttributeRouting.CSharp
Eleflex.Lookups.WebClient
Eleflex.Lookups.WebServer
gfoidl.Translator
N2CMS.Dinamico.DemoContent
Nuget_Package
MarkDown.Hermes
T4EmbeddedResources
Correspondence.Web.AllInOne
Mustachio.Rtf
XperiAndri.Interactivity.Orientation
Reinforced.Lattice.Templates.Mvc4
T4Config
linq2db.Oracle.Unmanaged
Mvc5CodeTemplatesCSharp
DataBooster.DbWebApi.Oracle.ODP
Autumn.Net.Data.SQLite.Mono
Zed.CRM.FreeMarker
Reinforced.Lattice.Bundle.Mvc5
MilNet.Services.AspNetCore
Fusonic.Extensions.UnitTests.Tools.PostgreSql
OpenRiaServices.Client.CodeGen
BooostersAcademy.AspNetCore.Logging
MoglooLib.GameData
Dynamo.RazorTemplates
Angular-Breadcrumb
TFSToolsetForTester
Appccelerate.SourceTemplates
T4DSG
EdiFabric.Templates.Hipaa
EntityFramework.CodeTemplates.VisualBasic
Leprechaun
Syncfusion.Xamarin.SfMaskedEdit
T4PocoGenerator
WebAPIDoodle.Bootstrap.Sample.Complex
RedRiver.Framework.XtraCommon
Ministry.EntityFrameworkRepositoryBuilder.DbContext.Ef6
Codeless.WaterpipeSharp
Retyped.swig-email-templates
ExternalTemplates.AspNet
Ducksoft.SOA.BL.Templates
Fogy.Core
Take.CustomerSuccess.Extensions
SendCloud.NET
EdiFabric.Templates.Padis
FNA.Package
RS.SAAS.EmailTemplater
Fortis.Codegen.Transitus
liquid.cli
MaltReport2
Touryo.Infrastructure.Public.Security
T4Resx.CSharp
Unofficial.Microsoft.TextTemplating.BuildTasks
Altairis.DynamicData.WebAppTemplates
Syncfusion.Xamarin.XlsIO
TestCustomLibrary.CustomFieldTemplates
ID.Bootstrap.Scaffolding.Templates
SL4PopupMenu
Onebin.OneT4.MultiLanguage
CodeSmith.Generator.BaseTemplates
TrackableEntities.CodeTemplates.Service.Net45
dropkick.settings.templates
Ministry.EntityFrameworkRepositoryBuilder.ObjectContext.Ef5
Reinforced.Lattice.Bundle.MvcCore
Nibble.Umbraco.UIOMaticT4Templates
ADDSBootstrapMVC
Rhetos.Wcf
GlobalParams
TrackableEntities.CodeTemplates.Client.TypeScript
Neodynamic.SDK.ThermalLabel
DotNetEmailTemplater
NTiering
ADee.Framework.BLL.CodeTemplates
emFrameworkCore.CodeGen
CsharpMacros
Penguin.Cms.Web.Mail.EmailRenderer
PG.Inspinia.TagHelpers
OpenDoc.Excel
Syncfusion.SfRadialMenu.UWP
MvcControlsToolkit.CoreTemplates.Bootstrap3
wpflipping
ADee.Framework.Model.CodeTemplates
oMapGen
SFS-Shell-Web-Mvc-Compiled
Magicodes.IE.Pdf
tooorangey.RssFeedUrl
T5.Templates
SharpDisasm
HotTowelTypescript
ContextItemsMsSql
ZayniFramework3.DataAccess.LightORM
MarcelDigital.Umbraco.Amp
Kingdom.CodeAnalysis.Verifiers.CodeFixes
FluTe
Cissy.Tools.Templates
Syncfusion.Xamarin.SfRadialMenu.IOS
CSharpDiscriminatedUnion.Generator
SwipeCollectionView
Bitcall.Common.Templates.Razor
Schommer.Projects.PBars
Empowered.NetCoreTemplates
Syncfusion.Xamarin.SfDataGrid.IOS
Syncfusion.SfRadialMenu.WPF
Tiger.Ctrls.CustomTemplates
Aspose.OMR-Cloud
moriyama.superdoctypecreate
Unic.PackMan.Sitecore7
MereGenerator
Unic.PackMan.Core.Sitecore7
Wisej-TourPanel
Unic.PackMan.Sitecore6
Syncfusion.XlsIO.AspNet.Mvc4
LiveReloadServer
Syncfusion.XlsIO.ClientProfile
Logging.StructuredLog4Net
RESTServices.Framework
XamarinFormsExtensions.Controls
armadillo-code
MentorWebBlocks.Core
Profound.Kentico.AMPPlugin
Magicodes.IE.AspNetCore
Neodynamic.SDK.ThermalLabel.Sample.WinForms.CS
Neodynamic.Windows.ThermalLabelEditor.Sample.WinForms.VB
Neodynamic.SDK.ThermalLabel.Sample.WinForms.VB
TestBase.Mvc.AspNetCore
Neodynamic.Windows.ThermalLabelEditor.NetCore
RazorEngine
TemplateEngine.Docx
Template
SEA.Template
Reinforced.Lattice.BootstrapTemplate
TemplateValidator
MvcCodeTemplate.Core
wxWidgetsTemplate
AppMobiWP8HelloWorldTemplate
TemplateTable
mustache-sharp
HotGlue.Template.Dust
HotGlue.Template.JsRender
Microting.eFormCaseTemplateBase
TemplateEngine.Docx-beta
feint-template-engine
IA.Framework.TemplateBot
Platform.Core.Data.Template
TemplateParser
Ziraff.Template
AppMobiWindows8DirectCanvasTemplate
Grebok.Template
Messaia.Net.Base.Template.Mapping
AutofacTemplate
RestTemplateCore
TwitterBootstrapMVC3Template
Single_Page_Template
SharpTemplate
AppMobiWP8ContactsTemplate
WhisperTemplate
Angular-UI-Material-Template
AppTemplate
SPAngularAppTemplate
Knockout.Bootstrap.TemplateStore
NPOI.Template.Excel
Takenet.MessagingHub.Client.ConsoleHostTemplate
WebsiteTemplateCore
NetCoreKit.Template.Standard
TwilioMvcTemplate
Philadelphia.Template
Platform.Delegates.TemplateLibrary
LogicAppTemplate
VSSDK.TemplateWizardInterface.12
Akka.Interfaced-SlimClient.Templates-Protobuf
Template10.Controls.ImageEx
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Serialization.Bson
Akka.Interfaced-SlimClient.Templates
Webezi.TemplateKit
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Serialization.Json
partners_igia_microservice_template
KDCLLC.WebOptimizer.AngularTemplateCache
ChameleonForms
Razor-Components-Template
IHAP.OfficeTemplate
CLK.AspNet.Identity.Mvc.Template
Atlas.CLI.Template
Knockout.Bootstrap.TemplateStore.Client
Kugar.Tool.ExcelTemplate
SmartCode.TemplateEngine
TechSurvey.Template
Platform.Collections.Methods.TemplateLibrary
Simplic.Utilities.TemplateParser.NoDep
TypeCobol.TemplateCore
Template10.Services.WebService
TemplateConnector
Template10.Services.MarketplaceService
Template_DDD
Template_SOLID
Nustache.Compilation
TBB.MessageService.WxTemplateMsg
Dynamic.EmailTemplate
aurelia-html-import-template-loader.TypeScript.DefinitelyTyped
LJH.Host.Template.Upload
ConnectorTemplateD
Palow.Template.Dotnet
ServiceTemplateNew
texttemplate
Stubble.Extensions.JsonNet
Stubble.Compilation
MicroserviceTemplate.API
Templator
AMDIT.DotNetCoreNTierTemplateLibrary
Daisytech.Web
OpenWaves.Templates.Navigation
Veil.Handlebars
RazorTemplatesMvc
Foundation3_MVC4
SiteTemplates.FormSite
MAH.Contracts
Fynix.Common.WebUI
SharpTAL
Bisque.Aws
Masb.Mvc.TableBuilder
GraphiteWeb.Swank
Vintasoft.Imaging.FormsProcessing.Wpf.UI
Templatus
mustache.js2
crispin
Eighty.AspNet.Mvc
PS.Core.Repository
ETK.Excel
ExampleProject.Mubassir.MVCCore
mustache-sharp-3.5
T4ConstructorGenerator
mailzor
Org.Reddragonit.MustacheDotNet
Zahasoft.Skele.UnitTest.Fsharp
gsl
MyCompany.MyLibrary
jQuery.Templates
Skywalker.Web.Mvc.ViewComponents
NVue
Red.HandlebarsRenderer
CubeBuild.JSRazor.Web.MVC
Red.EcsRenderer
RazorEngineFromXml
MetaCode.Generators
Generazor
DocumentMaker
PMoney.Templates
Stubble.Extensions.SystemData
EWSoftware.ListControls
MetaCode.Validator
Moca.NETWindowsFormProject
FluentEmail.Markdown
Javista.AttributesFactory
ZeraSystems.CodeNanite.Cshtml
FluffySpoon.Templates
ExpertCs.StringUtils
EasyPKIView
Framex.Core
MustacheCs
Moca.NETWebFormsProject
EJS
KMBPageFieldJS
CRMDocumentExtractor
AdminLteMvc
N2CMS.Management
AngularJs.SPA.Security
Capgemini.Xrm.Deployment.PackageDeployer
TypeScriptAngularJsProxyGenerator
JD_GetJobDetails
JD_GetGroupMembershipRepAccessList
JD_GetClientCategoryMapping
JDLog
Sphyrnidae.Client.Resource.Web
ndjango
OnionArchitecture.API
nTemplater
CSLA-Templates
aspose.html.sdk.v140
Boilerplate.Web.Mvc5
Demopakg
JD_SetBundle1
JD_BundleMediaSearch2
JD_GetPostedMediaJob4
Jdd_GetGroupBundleRepAccessList_WithoutOrganization
JD_GetPostedMediaJob2
JD_GetPostedMediaJob9
JD_SetBundle2
N2CMS.Mvc
NReco.PdfGenerator.LT
WebMarkupMin.Core
Correspondence.Web.App
MyMvcDemo
cpplinq
WebApiProxyClient
Enbd.Framework.Core
solutionfactory
PdfTemplating.XslFO.Razor.AspNet
MVC4NuGetDeno
Sites.Core
SuperScript.Templates.WebForms
Microsoft.AspNet.Mvc.ScaffolderTemplates.AttributeRouting.CSharp
WebApiProxyClientJS
Juipp.Core
T4AppSettings_Generic
Sphyrnidae.Server.Authentication.Web
DynamicDataTemplatesCS
Xenko.Samples.Templates
BravoAppClass
RoslynTester
linq2db.MySqlConnector
SPAppsSignalR
Synthesis
Karamunting.Android.GTuredi.StatefulLayout
RazorTemplates.Core
nBuildKit.MsBuild.Samples
linq2db.SapHana
James.ServiceStubs
Acrotech.Versioning
vici.core
EF4Templates
Touryo.Infrastructure.Framework
DocFx.Plugins.PlantUml
Autumn.Net.Logging.Log4Net
Vostok.Applications.Scheduled
ModelsToTypescript
Autumn.Net.Data.SQLite
Mvc4CodeTemplatesCSharp
Sphyrnidae.Client.Resource
DataBooster.DbWebApi.Oracle.DataDirect
Html5EditorTemplates
Datatables.Bootstrap4.Mvc
Eleflex.Email.WebServer
linq2db.Sybase.DataAction
MirkoProdSoluma
ConventionCodeFixVerifier
1.0.0.0
Weingartner.DotLiquidExtensions
MediaTrainer.Templating
Touryo.Infrastructure.Public.Db.DamPstGrS
LinkOS_Xamarin_SDK
Bolero.HotReload.Server
Touryo.Infrastructure.Framework.RichClient
Boilerplate.AspNetCore.Razor
BinbinMvcRazorTemplates
OrangeJetpack.Localization.Mvc
simple-t4-engine
NotAClue.DynamicData.CustomFieldTemplates
SubstituteApp
AndroidDesignerGenerator
DocuWare.UriTemplates
Open-Xml-PowerTools
Retyped.email-templates
Xrm.Oss.TemplatingLanguage.Sources
AnuitexTemplates.UpworkMonitor
EdiFabric.Templates.Edifact
MessTalk
SFS-EFPOCO1-Web-Mvc
Vash
SFS-EFPOCO1-BusinessObjects
BusinessCasual3
UnifiedFramework
Mvc3CodeTemplatesVB
PetaPoco.DBEntityGenerator
Altairis.Mvc.CodeTemplates
ZenTemplates
Ministry.EntityFrameworkRepositoryBuilder.ObjectContext.Ef6
UcdArch.Templates.Mvc
CodeFluentRuntimeClient
Syncfusion.Xamarin.SfRadialMenu
NuGetTemplatesPlus.Library
SwitchBlade.Sample
yesmarket.Templating.Razor
CodeGenerator.Core
TrackableEntities.CodeTemplates.Client.Net45
DesigntimeSourcecodeGenerator.lib
SolutionTemplates
Toxon.UrlTemplates
StronglyTypedViews
Magicodes.IE.Excel
Ministry.EntityFrameworkRepositoryBuilder.ObjectContext.Ef4
NPage
Ducksoft.SOA.DAL.Templates
ActiveIS.UmbracoForms.CustomEmail
Unic.PackMan.Core
Serilog.Enrichers.EventCode
SqlBinder
MVC.Umbraco
SmartExcelUploader
Vcc.TemplatesEngine
WorkAByte.NuGet.Packager.Core
ExcelGenerate
ADee.Framework.ViewModel.CodeTemplates
Magicodes.IE.Html
SimpleMembership.Mvc3.Sample
Ops.Resource.Core.HyperV.Image.Windows
cb.AspNet.Identity.EntityFramework.T4
GTR
Syncfusion.XlsIO.AspNet
Zahasoft.Skele.Docfx
Syncfusion.XlsIO.Wpf
Running.Mushroom.MailSender
ncuillery.angular-breadcrumb
Magicodes.IE.Word
ContextItemsOracle
Sanchez.Logger.Templates.Standard
NickTurner.Cake.Nick.Templates
Zahasoft.Skele.Unitest
TheLightSwitchToolbox.StronglyTypedChoiceLists.Server
Sdl.Dxa.Tridion.Templates
Salesforce.SDK.Universal
WinCopies.GUI.Templates
TransientErrorHandler
Bitcall.Common.Templates
DefaultECS.EntityFactory
Penguin.Web.Rendering
WPF.ListViewLayoutManager
ThirteenSides.Common.Email
Bitcall.Common.Mails.Templates
SiHan.Html.Templates
Mondop.Templates
Packer_TeamCity_BuildAgent
NickTurner.Cake.Nick.Templates.csproj
Syncfusion.Xamarin.SfMaskedEdit.Android
BusinessCasual4
FiveLimes.Sitecore.DeviceLayoutWizard
Constellation.Feature.ItemSorting
dotnet-labodotnettestresultsparser
Unic.PackMan.Core.Sitecore6
MentorWebBlocks
IronText
Nortal.Utilities.TextTemplating
Magicodes.IE.Csv
Ellumination.CodeAnalysis.Verifiers.CodeFixes
AutoCake.Release
Ellumination.CodeAnalysis.Verifiers.Diagnostics
WEBCON.BPS.2020.SDK.Libraries
PhoneMediaViewer
WEBCON.BPS.2019.SDK.Libraries
Ktos.Build.GitVersion
Bifrost.XAML.Phone
Schedulr
ColinChang.ConsulRestHelper
TestBase.Mvc
VSSDK.TemplateWizardInterface
XAct.IO.TemplateEngines.NVelocity
Freya.Types.Uri.Template
Nustache
TsSoft.Docx.TemplateEngine
Takenet.MessagingHub.Client.WebhookTemplate
Kralizek.Lambda.Template
SimpleSyndicate.UriTemplate
Ding.Web.Template
Lykke.AlgoStore.CSharp.AlgoTemplate.Models
StringTemplate4.Visualizer
ExcelTemplate
Psns.Common.Build.GithubTemplate
CitizenMatt.ReSharper.LiveTemplateCompiler
TypeWriter.SignalR.Proxy.Template
HotGlue.Template.NANO
HotGlue.Template.Mustache
Microsoft.VisualStudio.ExportTemplate
UriTemplate
GbemTemplate
Simplicode.ConfigurationTemplate
MvcGridScafoldingTemplate
Messaia.Net.Base.Template.Services
Castle.NVelocity
AdminLTE.Template
Simplic.Utilities.TemplateParser
AppMobiWindows8JqMobiTemplate
CrystalReports.TemplateEngine
Template10.Services.NetworkService
JD_Template
AdminLTE
GoC.WebTemplate-Components
IA.Framework.TemplateBot.Tests
MetaCode.TemplateSuite2.CLI
AppMobiWP8AccelerometerTemplate
Tofi.Framework.TemplateRendering
EmailHtmlTemplateMVC
Template10.Services.SerializationService
HappyForestTemplate
GoC.WebTemplate-Components.Core
Calendar.Template.VB2
HTTPlease.Core
Crosser.EdgeNode.Modules.TextTemplate
WinJs-HTML-Template
T4IncludeTemplate
MVVM_ModelEntity_t4_Template
Platform.Core.Data.Contracts.Template
ITOO.ExamEvalTemplate.ViewModel
DotVVM.Contrib.TemplateSelector
Tungsten.EventTemplate
Sunny.TemplateT4
T4MVC
Curly
Photo.Gallery.Template.VB2
NetCoreKit.Template.EfCore
Nager.TemplateBuilder
WpfTemplateLib.dll
Otc.PdfTemplate
Emtec.RazorEmailTemplate.Activities
babel-template.TypeScript.DefinitelyTyped
Otc.TemplateToPdf.Abstractions
CarloCGC.MonogameTemplate
NetCoreKit.Template.Rest.MongoDb
FA_ClassLibraryTemplate
Ajuro.Net.Template.Processor
NMyVision.TemplateWriter
Template10.Services.DialogService
TemplateTable.Unity3D.Json
TypeWriter.Proxy.Templates
EmojiSharp.Template
ServiceTemplate
Template10.Services.FileService
TemplateBasedDocumentGenerator
TemplateBot.Tests
ConnectorTemplate
MHAT.ConsoleApp.ProcessTemplate
EventSourceGeneratorTemplateAttributes.NET
TBB.MessageService.WxTemplateMsg.Senparc
Template10.Services.ResourceService
Elad.JsiiLibraryTemplate
Essential.Templating.Razor.Email
GSOFT.Template.Application.Shared
IHAP.OfficeTemplate.Utils
DbFirst.Template
Penguin.Cms.Template
MasterChief.DotNet.ProjectTemplate.WebApi
Template_SOLID_IComparer
OrleansInterface.NetCore.ProjectTemplate
Discord.BotTemplate
ConnectorTemplateDev
V33_Connector_Template
string-template.TypeScript.DefinitelyTyped
BlueearthRestTemplate
Dynamo.Templates.Core
Watt
JESAI.HtmlTemplate.Pdf.Core
Templater
Objectivity.Test.Automation.Common.Features
Tharga.Reporter
MailMergeLib
Objectivity.Test.Automation.Common.MsTest
JD_GlobalFields
Transformer.NET
NHandlebars
Veil
Clarius.TransformOnBuild-unofficial
PowerpointTemplater
Org.Reddragonit.Stringtemplate
Mailer.NET
DataGen.Singleton
Meerkat.Mailer
TownCrier
VBStyleAnalyzer
DotLiquid.Modules
PommaLabs.Liquimail
Farmer
DynoPdf.Client
Shared.Plugins
SharpLightReporting
GSF.Web.Security
groupdocs-assembly-dotnet
crispin.System.Web
Shared.Views
Gasconade
Gembed
crispin.razor
Vostok.Launchpad.Templates.Library
Durwella.Azure.ArmTesting.Build
linq2db.SqlServer
linq2db.PostgreSQL
Aspose.HTML-Cloud
Ocaramba.MsTest
Stringy
swxben.reporting.System.Web
ZeraSystems.CodeStencil.Contracts
MetaCode.Runtime
AngularBundle
MetaCode.Exceptions
Missive.Templates.Razor
OfficeOpenXml.Extends
JDCB
Coding4Fun.VisualStudio.Utilities.Internal
AssemblyReferencesTT
Templary
NDocUtil
DemoPkg
GrapeCity.ActiveReports.Core.Rdl
Snippet
ImageFinder
hw.T4Helper
N2CMS
LMB.GenericEntityBase
MsCrmTools.DocumentTemplatesMover
JD_BundleMediaSearch
Triarc.Web.Bundle.Angular
TamTam.NuGet.Umb.SiteBuilder.V7.V2.Binary
Mvc.JQuery.Datatables.Templates
Serilog.Sinks.ContextRollingFile
Quirco.Templater
AutoTexter
JD_GetJobDetail
MyMVC4Demo
JD_MemebershipDetail
EntityFramework.CodeTemplates.CSharp
tbb
RazorTemplates
GeneratorBaseBonsai
AJA.AdminLTE
JD_GetGroupMembershipList
Vintasoft.Imaging.FormsProcessing.UI
Breeze.WebApi
JDD_SetMembership
T4TS
JD_GetPostedMediaJob_12
M3W.TemplatedEmailHandler
Cassette.Hogan
AdminLTE3.MVC
JDD_GetBundle_WithoutOrganization_V2
JD_Getgroupbundle
Naos.Build.Conventions.VisualStudioProjectTemplates.Recipe
Naos.Build.Conventions.VisualStudioProjectTemplates.Feature.Test
sdmap
JD_SetBundleList
Dragon.Mail
OpenXmlPowerTools
Naos.Build.Conventions.VisualStudioProjectTemplates.Feature
Naos.Build.Conventions.VisualStudioProjectTemplates.Domain
MVVMTemplate
Boilerplate.AspNetCore
PdfTemplating.XslFO.Xslt
vellum.templates.blog
Spring.Rest.Testing
Epplus.Mapper
Eigen
Orchard.Theme.CustomLayoutMachine
nczcontrollibrary
N2CMS.Dinamico
cloudscribe.Email.Templating.Web
SuperScript.Templates.jQueryTmpl
Knockout.Bootstrap
SMSOneSQL
Eleflex.WebServer
Estat.Sri.Ws.Header.Default
Synthesis.Core
Hyperstore.DomainLanguage
Shaver
cppconlib
EasyDox
linq2db.SQLite.MS
Breeze.Server.WebApi.Core
XSockets.ItemTemplates
Eleflex.WebClient
Bounce.Config
TemplaterBonsai
Fugu.Templates.Razor
HBD.Mef.Mvc.ModuleRegister
LionSoft.T4TS
NarraSparkMvc.Plugin.Boilerplate
BrightstarDB
FsLab.Runner
Spring.Messaging.Amqp.Rabbit
Adminlte.Dashboard.Aghiad
Jeeves.Core
CareStoreService
Spring.Messaging.Amqp
Cassette.KnockoutJQueryTmpl
VsoApi.MsAgile.Entities
Silifalcon.CFDIDefinition
SyncSoft.CQRS.RazorEngine
vspte.vs2012
Reinforced.Lattice.Bundle.Mvc4
Reinforced.Lattice.Templates.Mvc5
TableList.Mvc.Core
TableList.Mvc
CareStoreDeviceDriver
WebApi.ControllerTemplates
TypeScriptGenerator
Syncfusion.XlsIO.Net.Core
Dapper.FastCrud.ModelGenerator
LamedalCore_Templates
Devon4Net.Application.WebAPI.Configuration
Nustache.i18n
CodeGenerator.Templates.EF6-CQRS-Aurelia
cloudscribe.SimpleContent.ContentTemplates.Bootstrap4
DragAndDropMultiSelectorList
Tang.Library.Email
PortableRazor.StarterPack
Touryo.Infrastructure.Public.Db.DamManagedOdp
ZayniFramework.DataAccess.LightORM
T4Configuration
Templates
AsyncGenerator
PdfCardGenerator
SchneiderWixInstaller
FastUpload.Project
IsolatedRazor
HoopyFrood
MtDotNet
Blade
EntityNetwork.Templates
twig.twig
mt
24News
SFS-EFPOCO1-BusinessObjects-EF4
ExternalTemplates.Mvc
Vuets
RazorClientTemplates
TS.CodeGenerator
TestCustomLibrary3.CustomFieldTemplates
SFS-EFPOCO1-BR
Ministry.EntityFrameworkRepositoryBuilder.DbContext.Ef5
Razorback
MSHMI
RazorSharpEmail
Sitecore.ItemBinding.CodeGeneration.Tds
DesigntimeSourcecodeGenerator.T4
Microsoft.AspNet.WebApi.ScaffolderTemplates.AttributeRouting.VisualBasic
Fuko.PlaceHolders
Unic.PackMan
KinectContribTemplates
Kivii.Templates.B001
TrackableEntities.CodeTemplates.Shared.Portable
MSCTP.Office.NetCore
sh2ezo.utils.PseudoRandomTextGenerator
BrightlineJS
Mandrill-Dotnet-Temp
TemplatedQuery
ScaffR.Bootstrap.Templates
swig-email-templates.TypeScript.DefinitelyTyped
Wisej-2-TourPanel
Karkas.Templates.Mvc4
RazorEngineCore.Precompiler
Syncfusion.SfGrid.WPF
PSS.TextTemplating.StaticDataLibrary
WebPx.AdminLTE.AspNetCore
Ajuro.Net.Templater
DynamicCalendar
Rocket.Surgery.Templates
Aspose.Pdf-Cloud
Syncfusion.XlsIO.WinForms
Syncfusion.Xamarin.SfPicker.Android
Gaia.Core.Mail.RazorEngineTemplates
WPF.Notifier
SharpDocx.Fork
gulp-angular-templatecache.TypeScript.DefinitelyTyped
NPoco_Identity_Provider
Syncfusion.Xamarin.SfPicker.IOS
Syncfusion.XlsIO.UWP
BioEngine.Extra.ContentTemplates
FluentEmail.RazorTemplates
Xopz.Templates.Api
Salesforce.SDK.SmartStore
SimpleJinja2DotNet
ExtendedControls.ExtCollectionView.XForms
linq2db.DB2.Core
TestBase-Mvc
Syncfusion.Xamarin.SfMaskedEdit.IOS
Chaos.Tool.TemplatedOutput
Sanchez.Logger.Templates.Scoped
Bitcall.Common.Templates.Abstractions
Senner007Corporation.Mvc.Templates
PortalTemplates
Syncfusion.Xamarin.SfDataGrid.Android
Tyingsoft.Sln
Smith.BuildExtensions
GUAP.MvcTemplates
Syncfusion.SfTreeNavigator.WPF
Constellation.Sitecore.Items
RTextProcessing
ST4bby
ZumeroDataGrid
JmpCoreMailer
UnistrokeRecognizer.UWP
Xamarin.Forms.SavableObject
Essential.LoggerProvider.RollingFile
OliveGameStudio.Inferno.Infrastructure.DataTransferObjects
Constellation.Foundation.Items
Idea42.NuGet.AngularSPA.Lumx
RazorEngineCore.TestComputers
Static.Voyager
Neodynamic.Windows.ThermalLabelEditor.Sample.WinForms.CS
armadillo-code-only
iTextSharp.PdfHelpers
Syncfusion.SfTreeView.WPF
Syncfusion.Xamarin.SfDataGrid.WPF
TestBase.AspNetCore.Mvc
Template10
Knockout.js_External_Template_Engine
XAct.IO.TemplateEngines.StringTemplate
Takenet.MessagingHub.Client.Template
T4.TemplateFileManager
UriTemplate.Core
SpaTemplateHelpers
NLightTemplate
SpaTemplateHelpersUnsafe
CodeGenHero.Template
PersistentRetryTemplate
Wyam.Blog.BlogTemplate
Messaia.Net.Base.Template.Models
Angular-Template-Bundler
DocCreator.TemplatePackage
JD_TemplateData
HotGlue.Template.jQuery
Backbone.TemplateService
Amusoft.VisualStudio.TemplateGenerator.CommandLine
Absolunet.InRiver.IPMC.HtmlTemplate.Core
HotGlue.Template.doT
Lykke.Service.TemplateFormatter
Kralizek.Lambda.Template.Sns
Angular.TemplateRender
DocCreator.TemplatePackage.Offline
StringTemplate.MSBuild
TemplateTable.Protobuf
ConsumerTemplate
ITOO.ExamEvalTemplate.Service.Contract
Lykke.TemplateFormatter
Tavis.UriTemplates
SkbKontur.Excel.TemplateEngine
infuser
DS.Connector.Template
OrleansSiloHost.NetCore.ProjectTemplate
UriTemplateString
Clarius.TransformOnBuild
Messaia.Net.Base.Template.Repositories.Impl
CustomTemplate
Template_Adoptor
GoC.WebTemplate-CoreMVC
INSM.Template.Framework.v1
ApiTemplate
WebApi.Setup.Template
ShapeTemplateLib
Katalina.TemplateParser
Xpertdoc.TemplateManager.AddIn
Angular2-Template-for-MVC-and-WebAPI
IPEIT.TemplateResolver
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Console
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Assembly
TemplateBot
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Recipe.Test
NugetTemplate
TemplateSvcContract
OBeautifulCode.Build.Conventions.VisualStudioProjectTemplates.Domain
NetCoreKit.Template.MongoDb
AspenDigital.Template.Common
Cottle
TypeCobol.TemplateTranspiler
24SevenOffice.MappedApi.Template
TwilioWebApiTemplate
Wilinq.ProcessTemplates.Agile
VSSDK.TemplateWizardInterface.10
Dapper.SimpleCRUD.ModelGenerator
NetCoreKit.Template.Rest.EfCore
EventCentric.Node.ServerTemplate
EasyArchitect.BO.ServerComponent.ServiceTemplate
TeamBuild.ScriptTemplate
Aurigma.GraphicsMill.Templates.x86
MoonMachine.StrategyTemplate
JavaScript-Templates
url-template.TypeScript.DefinitelyTyped
TH.Utility.EnhancedConsoleApplicationTemplate
Jaba.J6.NotificationTemplate
Platform.Hashing.TemplateLibrary
IVySoft.VPlatform.TemplateEngine
GSOFT.Template.Application
GSOFT.Template.Core
Informedica.Build.Template
Sugar.BaseTemplate
Foundation5.MVC
V33_Connector_Template33
Mustache.NETStandard
Refactored.UmbracoEmailExtensions
VirtualTemplates
knockout.pager
swxben.docxtemplateengine
NRest
Foundation5.MVC.Sass
Vintasoft.Imaging.FormsProcessing
CarlitoCoorporate.MyTestSolution
fm.Extensions.Wpf
warmup
Foundation4.MVC4
GraphiteWeb.Views
grazewp7
HBD.Services.Transformation
Veil.SuperSimple
AdolphaService
HtmlTableHelper
Mustache.PCL
Zahasoft.Skele.Library
Ocaramba.Features
Coravel.Mailer
SPATools.UI.Base
NetExcel
CodeSmith.Generator.EntityFramework
Regextra
DD4T.Templates.Base
TnCouchbaseClient
CustomMayd.Services.Serialization
Earl
T4ResX
Boxed.DotnetNewTest
Csx.Core
Shared.Images
Rsft.EmailContentMerge.Markdown
RoguelikeToolkit.Entities
Jefferson
Vostok.Launchpad.Templates.SourceLibrary
WuffProjects.CodeGeneration
MetaCode.TextProcessing
Allors.Documents
PostageApp.Net
HatTrick.Text.Templating
MetaCode.CLI
Angular4
dotnet-vstemplate
MetaCode.Models
MetaCode.CGDLParser
VirtualPathTemplates
Coding4Fun.VisualStudio.Telemetry
NReco.PdfGenerator
RunningObjects.Templates.Default
XamlColorSchemeGenerator
PostageApp
ServiceStack.Host.Mvc
Xtensive.Orm.AppConfig
Cassette.Aspnet
Templar
HotTowelette
HotTowel.Angular.Breeze
FormFactory.Templates
Neptuo.Templates.Compilation
DataElement
100
JD_BundleMediaData
AngularTemplates.Compile
Tmp.Distribution.Client.GetJobDetail
JD_GetMEmbership
JD_MemebershipDetail2
Blackbaud.ToolsFx.Build
JD_SetBundle
Ci.Office.Helper.OpenXml
CodesnippetPackage
layout.mvc5
JDD_GetMediaFieldHtmlTags
Templ.NET
Missive.Templates.Simple
MembershipDemo
JD_GetPostedMediaJob
JD_GetPostedMediaJob_10
N2CMS.ReusableParts
Toolkit.Snippets
JDD_GetUnfinishedJobMediaForJob
ClickTwice.Templates.SolidState
linq2db.Firebird
Essential.Diagnostics.Structured
JD_GetPostedMediaJob_14
Naos.Build.Conventions.VisualStudioProjectTemplates.Serialization.Bson
N2CMS.Bundles.Dinamico
SesiMaterialAdminMvc
Zebble.ListView
Naos.Build.Conventions.VisualStudioProjectTemplates.Bootstrapper
SuperScript.Templates
SFSdotNet-Framework-Security-Web-Mvc
T4MVC.SharpDevelop
Microsoft.Orleans.Templates.Grains
SuperScript.Templates.JavaScriptTemplates
Unofficial.Microsoft.VisualStudio.TextTemplating
VrsekDev.Blazor.Templates.MajesticAdmin
T4WebFormsInjection
ApiNCoreE.VSIX
T4Decorators
CareStoreWpfApplication
Storm.T4
linq2db.DB2
Boilerplate.Web.Mvc6
Bootstrap.MVC.EditorTemplates.Sample
NewLife.XTemplate
Simplify.Templates
PugViewEngine
KODataTable
T4Immutable
blitz
Gofer.Sample
MirkoTestSoluma
NServiceKit.Host.AspNet
memberpage
IceWpfApplication
Boilerplate.AspNetCore.TagHelpers
vspte
twitter.bootstrap.mvc4.templates
NServiceKit.Host.Mvc
C1.LightSwitch.Olap.Server
AKS.CodeGenerator
Swasey
DataBooster.DbWebApi.Oracle.Managed
DataBooster.DbWebApi.SqlServer
Autumn.Net.Data
DynamicDataTemplatesVB
MVCSearchEngine
adjunct-System.Text.TemplatedTextService
Syncfusion.Xamarin.SfPicker
BSharp.Core.RazorToPdf
CreatioSDK
Suamere.QuestionAnswer
GPS.Seq.Slack
Devon4Net.Infrastructure.Common
Hy.Modeller.Tool
Touryo.Infrastructure.Public.Db.DamMySQL
Eleflex.Email.WebClient
Codeless.Data
JQueryListBinding
ScenarioObjects
NarraSparkMvc.Boilerplate
ApiNCoreD.VSIX
Syncfusion.Xamarin.SfDataGrid
Skyhop.Mail
jquery.easing.mvc
Reinforced.Lattice.Templates.MvcCore
RazorEmail
TestCustomLibrary5.CustomFieldTemplates
iridium.script
Fogy.NLog
Csla.Templates
Hydrogen
OneClickTestCaseBindingTool
Ducksoft.SOA.Adaptors.Templates
SimpleSyndicate.Mvc.EditorTemplates
Essential.Diagnostics.RollingXmlTraceListener
WebAPIDoodle.Bootstrap.Sample
FileTextReplace
FunScript.TypeScript.Binding.uri_templates
AspSpaSilo-GH
T4.Samples
SourceCharm.TestRunner
ConfigBuilder
TrackableEntities.CodeTemplates.Shared.Net45
EventsDialog
EdiFabric.Templates.Vda
Underscore.Templates.MsBuild
SFS-EFPOCO1-BusinessObjects-EFPocoAdapter
Microsoft.AspNet.Mvc.ScaffolderTemplates.AttributeRouting.VisualBasic
Zebble.Grid
Izio.Umbraco.ContentUtilities
TrackableEntities.CodeTemplates.Client.Portable
Wrox.ProMvc4.Ajax.Templates
NotMicrosoft.Configuration
GroupDocs.Assembly
jquery.chosen.mvc
Tabler
Linn.Core.Templates
TemplatedConfiguration
Vizioz.PalettePicker
LibADCA
OO.Products
Soup2Nuts.CodeTemplates.EF.CSharp
CodeGecko.Packages.Umbraco.Sitemap
SysCommand
DoNUT
Gaia.Core.Mail.RazorLightTemplates
Sitecore.Support.IndexHealthMonitor
Ops.Resource.Core.HyperV.Resource.Windows
ADee.Framework.DAL.CodeTemplates
Smetko.Paging.Mvc
Syncfusion.SfTreeNavigator.UWP
FlexNet.Templates.SimpleTCP
Syncfusion.XlsIO.AspNet.Mvc5
AdatumCorporation.Utility.Templates
LagDaemon.Templates.FSharp
TestBase";
    }
}
