using System;
using System.Collections.Generic;
using System.Text;

namespace TemplatesShared {
    internal static class Strings {
        internal static readonly string NuGetQueryBaseUrl = "https://azuresearch-usnc.nuget.org/query";

        internal static readonly string PackagesToIgnore = @"eTemplates.Shared.Net45
TrackableEntities.CodeTemplates.Shared.Portable
Transformer.NET
TransientErrorHandler
Trarc.Web.TemplateEngine
Triarc.Web.Bundle.Angular
Tribe.Template
TS.CodeGenerator
TsSoft.Docx.TemplateEngine
TweetSharp
TweetSharp.WindowsPhone
TweetSharp-Unofficial
twitter.bootstrap.mvc4.templates
TwitterBootstrapMVC3Template
TXTextControl.Web
TypeLess.Mail
TypeLite.Lib
TypeScriptAngularJsProxyGenerator
TypeScriptGenerator
typescripttemplates
UcdArch.Templates.Mvc
uibuilder
UmbCodeGen
UmbracoTemplateEngine
Underscore.Templates.MsBuild
UnderscoreBundler
Underskrift.Client
Unic.PackMan
Unic.PackMan.Core
Unic.PackMan.Core.Sitecore6
Unic.PackMan.Core.Sitecore7
Unic.PackMan.Sitecore6
Unic.PackMan.Sitecore7
Unicorn
Unicorn.Core
UnifiedFramework
UnistrokeRecognizer.UWP
UnitTestGenerator
UnitTestGenerator.Extensions.Composition
Unofficial.Microsoft.VisualStudio.TextTemplating
Unofficial.Nustache
UriTemplate.Core
uri-templates.TypeScript.DefinitelyTyped
UriTemplateString
url-template.TypeScript.DefinitelyTyped
Utils.NET
Vash
Veil
Veil.Handlebars
Veil.SuperSimple
vici.core
Vintasoft.Imaging.FormsProcessing
Vintasoft.Imaging.FormsProcessing.Wpf.UI
VirtualPathTemplates
VirtualTemplates
VsoApi.MsAgile.Entities
vspte
vspte.vs2012
VSSDK.TemplateWizardInterface
VSSDK.TemplateWizardInterface.10
VSSDK.TemplateWizardInterface.11
VSSDK.TemplateWizardInterface.12
VSSDK.TemplateWizardInterface.8
VSSDK.TemplateWizardInterface.9
warmup
Watt
WebApi.ControllerTemplates
WebApi.Setup.Template
WebApi.Template
WebAPIDoodle.Bootstrap
WebAPIDoodle.Bootstrap.Sample
WebAPIDoodle.Bootstrap.Sample.Complex
WebApiProxyClient
WebApiProxyClientJS
WebHttpBehaviorExtensions
WebMarkupMin.Core
WebSharper.Templates
Weingartner.DotLiquidExtensions
Westwind.RazorHosting
Win8Controls
WinJs-HTML-Template
WINRTNotifications
Wired.Razor
Wishlist.Template
WordCleaner
WorkAByte.NuGet.Packager.Core
WPF.Notifier
wpflipping
WpfTemplateLib.dll
Wrox.ProMvc3.Ajax.Templates
Wrox.ProMvc4.Ajax.Templates
wtl
WuffProjects.CodeGeneration
wxWidgetsTemplate
XAct.IO.TemplateEngines.NVelocity
XAct.IO.TemplateEngines.RazorHost
XAct.IO.TemplateEngines.StringTemplate
XActDependency.Antlr3.StringTemplate
XamarinFormsExtensions.Controls
xercesc
Xerneas.Template
XperiAndri.Interactivity.Orientation
Xpertdoc.TemplateManager.AddIn
Xpertdoc.TemplateManager.Operations
Xpertdoc.TemplateManager.Operations.Word
xscaffolding
xscaffolding.tempates
XsdClassGen
XSockets.ItemTemplates
Xtensive.Orm.AppConfig
XtraLiteTemplates
Y3
Yeoman.VisualStudio
yesmarket.Templating.Razor
Yodii.Script
ZenTemplates
ZenTemplates.HttpHandler
ZKWeb.Fork.DotLiquid
ZumeroDataGrid
Zurb_Foundation_MVC3
Zurb_Foundation_MVC3_Demo
AngularCSharp
AspNetMvc.Template.AccountController
AspNetMvc.Template.Empty
AspNetMvc.Template.Internet
Black.Beard.Sdk.Net.Mails
BLDR.Test
Boilerpipe.Net
Boilerplate.AspNetCore
Boilerplate.AspNetCore.Razor
Boilerplate.AspNetCore.Swagger
Boilerplate.AspNetCore.TagHelpers
Boilerplate.Web.Mvc5
Boilerplate.Web.Mvc6
Boilerplate.Web.Mvc6.Razor
Boilerplate.Web.Mvc6.TagHelpers
BorisMoore.JsRender
Catapult.Peanut.Atlatl
Code4U
CodeSmith.Generator.EntityFramework.WebAPI
ConsulTemplate.Core
DD.CBU.CaasDeploy.Library
DD.CBU.CaasDeploy.Orchestration.Docs
Enjoy.Templates
Freya.Routers.Uri.Template
Freya.Routers.Uri.Template.Hopac
Freya.Types.Uri.Template
FsMessageTemplates
FsMtParser
Fx.AppServer.Main
Happy
HTTPlease
HTTPlease.Core
ImmutableObjectGraph.T4
knockroute
Leprechaun
Mail.Razor
mantle-worker-azure-cloud-service-role-host
mantle-worker-console-host
mantle-worker-template
mantle-worker-windows-service-host
MessageTemplates
Microsoft.AspNet.DynamicDataTemplates.CS
Microsoft.Data.Services.Client.T4
MonoGame.Template.Platformer2D
mustache-portable.kre
NecroNetToolkit.RepositoryGenerator
Newtonsoft.Json
NokauTemplate
NPolyglot.Templating.Handlebars
Octopus.Tfs
pecan-waffle-vs
Protobuild.Template.Console
Protobuild.Template.Library
Protogame.Template.Asteroids
Protogame.Template.Blank
Protogame.Template.Platformer
Rackspace.Net.UriTemplate
RapidSP.SqlServer
RazorEmailCore
RazorEngine.Roslyn
Reactive.Caliburn.Avalon.Metro
Reactive.Caliburn.Metro
SEBSET
Shared.Images
Shared.Plugins
Shared.Scripts
Shared.Styles
Shared.Views
ShortBus.Scaffolding
Simplr.MVC.WebsiteTemplate
SSW.DataOnion.DbContextGenerator.EF6
StackExpress.Razor
StackExpress.Razor2
Stubble.All
Stubble.Core
Stubble.Extensions.JsonNet
Stubble.Extensions.Loaders
Stubble.Extensions.SystemData
Swagger.WebApiProxy
Tempest
Tempest.Generator.Empty
Tempest.Generator.New
TemplateJS
Temptress
TunnelVisionLabs.Net.UriTemplate
Turnip.MSBuild.Task
VsTemplar
Xania.EntityFramework
Zafir.Templates
Kralizek.Lambda.Template
Newtonsoft.Json";
    }
}
